### PR TITLE
Fix system tray icons

### PR DESCRIPTION
**Pull request by gombosg**

### CODE REVIEW

**Comment by pktiuk** [comment]
I think it would be good to check how other packages deal with displaying tray icons.  
Like https://github.com/flathub/com.slack.Slack

**Comment by pktiuk** [comment]
Maybe we should also ping original contributor of this change.

**Comment by gombosg** [comment]
Success, removing this line makes the tray icon working on GNOME again.
Adding `--own-name=org.kde.*`, maybe that fixes the issue. Can it interfere with other Flatpak apps though?

Relevant commits:
https://github.com/flathub/im.riot.Riot/issues/100
https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/commit/518e7c06718f211966a6231a87e57090968e911d
https://github.com/flathub/org.keepassxc.KeePassXC/commit/362a037832c2e653eb2bf98d75eaf352c17ca3c3
https://github.com/flathub/us.zoom.Zoom/commit/348ff4e59ac6cc8104a729710dd11dba67147f51
https://github.com/flathub/com.dropbox.Client/commit/a0594d16997f6f9c65919d0c8afd056137737957

**Comment by gombosg** [comment]
Test result: see [here](https://github.com/AntiMicroX/antimicrox/issues/58#issuecomment-703448675).

**Comment by gombosg** [comment]
Merging this now until we figure out what is wrong with the tray icon.

**Pull request merged**
